<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>1fe88f77-fe86-448a-9bcb-0d5488c85dd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[24]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.p-element.p-ripple.p-datepicker-trigger.ng-tns-c83-43.p-button.p-component.p-button-icon-only.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>353cee17-b8b8-4bfe-9909-baba748a71c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3117fa7c-cd14-40da-aa77-91e7ccbe0fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>283d945a-8928-43a8-b174-824c3f3353a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element p-ripple p-datepicker-trigger ng-tns-c83-43 p-button p-component p-button-icon-only ng-star-inserted</value>
      <webElementGuid>aa4e7b2b-1321-4228-95bb-f866b5eb81bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>c0fd21a3-80d5-491a-b5ec-130e3d133df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-5&quot;)/jhi-payablegw-dokpostkontrak-list[1]/jhi-payablegw-formdokpostkontrak[1]/p-dialog[@class=&quot;p-element ng-tns-c110-41 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c110-41 p-dialog-mask p-component-overlay p-component-overlay-enter p-dialog-mask-scrollblocker ng-star-inserted&quot;]/div[@class=&quot;p-element ng-trigger ng-trigger-animation ng-tns-c110-41 p-dialog p-component ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c110-41 p-dialog-content&quot;]/form[@class=&quot;ng-valid ng-star-inserted ng-dirty ng-touched&quot;]/div[@class=&quot;grid -mx-1&quot;]/div[@class=&quot;col-12 px-1&quot;]/div[@class=&quot;field grid -mx-1&quot;]/div[@class=&quot;px-1 col-3&quot;]/p-calendar[@id=&quot;tanggal&quot;]/span[@class=&quot;ng-tns-c83-43 p-calendar p-calendar-w-btn&quot;]/button[@class=&quot;p-element p-ripple p-datepicker-trigger ng-tns-c83-43 p-button p-component p-button-icon-only ng-star-inserted&quot;]</value>
      <webElementGuid>e1003064-c277-4266-8521-49b388b0f410</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[24]</value>
      <webElementGuid>69b84675-6c3a-4248-b65d-e10cff1b2ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//p-calendar[@id='tanggal']/span/button)[2]</value>
      <webElementGuid>f69d0b96-ead9-4a89-97ce-b2fe8594e8bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal'])[3]/following::button[1]</value>
      <webElementGuid>ba283eb2-effe-4b41-8f91-29fe4440a738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[3]/following::button[1]</value>
      <webElementGuid>5f34ce5a-1503-45a5-b54b-f927f2a44be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama'])[3]/preceding::button[1]</value>
      <webElementGuid>5b4b42a9-a7f0-4d09-aaac-ffd7e3853d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keterangan'])[4]/preceding::button[1]</value>
      <webElementGuid>8cc8736d-5947-41d6-a242-8be555d4bdb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div/div/div/div[2]/p-calendar/span/button</value>
      <webElementGuid>89224bcf-78d9-4a26-81ed-5ea1b3746ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' ' or . = ' ')]</value>
      <webElementGuid>adbf650e-7792-4d1b-b5c8-648d348e4548</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
