<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama_namaDok</name>
   <tag></tag>
   <elementGuidId>199c047b-da7a-44e6-bb53-3bf720fae688</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='namaDok']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#namaDok</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10799d46-3616-48b8-89f0-77f68b4eab9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>namaDok</value>
      <webElementGuid>8e947cf6-adbf-40c1-bd60-91ca944b8525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>namaDok</value>
      <webElementGuid>a554d705-ee1e-425a-9ecd-92037d04e8ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>db143d99-3349-4ea6-a469-103d08e23f57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm text-color surface-overlay p-2 border-1 border-solid border-500 appearance-none outline-none focus:border-primary w-full h-custom ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>1ab753c8-d769-4e24-8983-033d72a86586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;namaDok&quot;)</value>
      <webElementGuid>a9ab5094-f652-4c82-b58e-6ae6aafbb812</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='namaDok']</value>
      <webElementGuid>dc4ea29a-b831-45c0-9f7b-fe48a0645e77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p-tabpanel-5']/jhi-payablegw-dokpostkontrak-list/jhi-payablegw-formdokpostkontrak/p-dialog/div/div/div[2]/form/div/div[2]/div/div/input</value>
      <webElementGuid>ede79640-217e-4124-bd61-02ae7d6de3d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>7768377c-fcdf-4644-bc6e-c0de2b745db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'namaDok' and @type = 'text']</value>
      <webElementGuid>b4c46a8c-fb12-4b53-a775-e53a66feea4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
