<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_9</name>
   <tag></tag>
   <elementGuidId>fd73d7b7-4b97-4118-a406-0e08d14dcc2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p-calendar[@id='tanggal']/span/div/div/div/div[2]/table/tbody/tr[3]/td/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.ng-tns-c83-43.p-datepicker-today.ng-star-inserted > span.p-ripple.p-element.ng-tns-c83-43.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>75729c34-536d-41c6-aeea-26069d64b389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f01775d6-8c10-4574-9427-2937d7dfec72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-element ng-tns-c83-43 ng-star-inserted</value>
      <webElementGuid>073ecb86-58c5-4b07-8fec-0770b51f10a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>259d526b-db95-4914-9e4b-ded4a8dd0504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>3cc684cb-8bc3-43ad-9222-b82eb029aeb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-5&quot;)/jhi-payablegw-dokpostkontrak-list[1]/jhi-payablegw-formdokpostkontrak[1]/p-dialog[@class=&quot;p-element ng-tns-c110-41 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c110-41 p-dialog-mask p-component-overlay p-component-overlay-enter p-dialog-mask-scrollblocker ng-star-inserted&quot;]/div[@class=&quot;p-element ng-trigger ng-trigger-animation ng-tns-c110-41 p-dialog p-component ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c110-41 p-dialog-content&quot;]/form[@class=&quot;ng-valid ng-star-inserted ng-dirty ng-touched&quot;]/div[@class=&quot;grid -mx-1&quot;]/div[@class=&quot;col-12 px-1&quot;]/div[@class=&quot;field grid -mx-1&quot;]/div[@class=&quot;px-1 col-3&quot;]/p-calendar[@id=&quot;tanggal&quot;]/span[@class=&quot;ng-tns-c83-43 p-calendar p-calendar-w-btn&quot;]/div[@class=&quot;ng-trigger ng-trigger-overlayAnimation ng-tns-c83-43 p-datepicker p-component ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-group-container ng-tns-c83-43 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-group ng-tns-c83-43 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-calendar-container ng-tns-c83-43 ng-star-inserted&quot;]/table[@class=&quot;p-datepicker-calendar ng-tns-c83-43&quot;]/tbody[@class=&quot;ng-tns-c83-43&quot;]/tr[@class=&quot;ng-tns-c83-43 ng-star-inserted&quot;]/td[@class=&quot;ng-tns-c83-43 p-datepicker-today ng-star-inserted&quot;]/span[@class=&quot;p-ripple p-element ng-tns-c83-43 ng-star-inserted&quot;]</value>
      <webElementGuid>0ee6d0e0-0479-4184-8ecd-a6585cefbc13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-calendar[@id='tanggal']/span/div/div/div/div[2]/table/tbody/tr[3]/td/span</value>
      <webElementGuid>2dd3d6ac-88d8-450b-a4b1-1ff9a67b3950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[29]</value>
      <webElementGuid>01ac5fb5-e0c2-4b34-bee7-9230a9c06f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::span[30]</value>
      <webElementGuid>e366fb6f-fcac-4f7b-8dfe-012815335fe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama'])[3]/preceding::span[56]</value>
      <webElementGuid>d5e2704e-b110-43b2-8858-3bc5e8f37467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keterangan'])[4]/preceding::span[56]</value>
      <webElementGuid>87bcd9a2-f5ef-448b-9145-921d4fc6fde7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='9']/parent::*</value>
      <webElementGuid>e678048a-f286-416d-8899-fd6df1fa9860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/span</value>
      <webElementGuid>37344f28-b7f0-485f-9ecd-1ff1bdfb3a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '9' or . = '9')]</value>
      <webElementGuid>9968e4a6-7b50-4d49-902c-0e71e1d17b61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
