<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan</name>
   <tag></tag>
   <elementGuidId>ab5555dd-6bb4-486b-a5a6-7fd815d2087e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.p-ripple.p-element.p-button-text.p-button.p-component</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[25]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d75a4cc9-9438-4d06-b1ab-a75ec836411e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-element p-button-text p-button p-component</value>
      <webElementGuid>402c214a-1069-4255-9cad-a5a1f3e18c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9b1e5d91-ef8d-41fb-b789-f8507b2fecf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>673c33f6-6f6e-45c0-8ab9-24151a9c9588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-4&quot;)/jhi-payablegw-termin-list[1]/jhi-payablegw-formsyrtbayar[@class=&quot;ng-star-inserted&quot;]/p-dialog[@class=&quot;p-element ng-tns-c110-44 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c110-44 p-dialog-mask p-component-overlay p-component-overlay-enter p-dialog-mask-scrollblocker ng-star-inserted&quot;]/div[@class=&quot;p-element ng-trigger ng-trigger-animation ng-tns-c110-44 p-dialog p-component ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c110-44 p-dialog-content&quot;]/form[@class=&quot;ng-valid ng-tns-c110-44 ng-dirty ng-touched&quot;]/p-toolbar[@class=&quot;p-element&quot;]/div[@class=&quot;mb-4 justify-content-end p-toolbar p-component&quot;]/div[@class=&quot;p-toolbar-group-right ng-star-inserted&quot;]/div[@class=&quot;my-2 ng-star-inserted&quot;]/p-button[@class=&quot;p-element&quot;]/button[@class=&quot;p-ripple p-element p-button-text p-button p-component&quot;]</value>
      <webElementGuid>4bd4c71e-910b-4d6a-96b1-d206a347bd42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[25]</value>
      <webElementGuid>95e19c1a-d158-46d6-a7e6-c252b04f31a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p-tabpanel-4']/jhi-payablegw-termin-list/jhi-payablegw-formsyrtbayar/p-dialog/div/div/div[2]/form/p-toolbar/div/div/div/p-button/button</value>
      <webElementGuid>aff170e3-dc8d-4ee3-b639-98dd9a3a9fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokumen Baru'])[2]/following::button[1]</value>
      <webElementGuid>1910f501-c9e9-4b4d-a0ae-944eff473657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokumen Baru'])[1]/following::button[1]</value>
      <webElementGuid>4bcd6c8e-b12c-4c8b-a07c-10755e4e9f34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluar'])[1]/preceding::button[1]</value>
      <webElementGuid>f40cbe31-3c4e-4202-8c2e-6449b7d943c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-button/button</value>
      <webElementGuid>26dd72e9-e212-4646-961d-5e7b29accdcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Simpan' or . = 'Simpan')]</value>
      <webElementGuid>85f63952-5766-4f7b-82dc-8b96a66329db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
