<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Dokumen_dokumen</name>
   <tag></tag>
   <elementGuidId>c7354501-dfc5-4e7c-a8b1-7de0472a58e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dokumen</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='dokumen']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>af0a0de1-aaa3-4a2b-ad59-5ab910ca4f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dokumen</value>
      <webElementGuid>eabb861f-8c54-4a76-b8b5-2d93d5b37148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>dokumen</value>
      <webElementGuid>2e0df2f6-4177-48c4-945d-965cf490c39f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b905ecf0-7021-4d68-bcb8-320690f5138b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a3893f6c-f98f-4213-8335-002c853ecb40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-base text-color surface-overlay p-2 border-1 border-solid border-500 appearance-none outline-none focus:border-primary ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>e0edbb73-cf36-4c27-abae-433611595e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dokumen&quot;)</value>
      <webElementGuid>f813ed2d-73c4-4a08-987c-178bab63b621</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='dokumen']</value>
      <webElementGuid>cc960db2-b449-4474-bd33-a045415db54e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p-tabpanel-4']/jhi-payablegw-termin-list/jhi-payablegw-formsyrtbayar/p-dialog/div/div/div[2]/form/div/div/div/div[2]/textarea</value>
      <webElementGuid>4eafbbfd-d971-46f9-be77-ca30359888b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/textarea</value>
      <webElementGuid>ba5115e3-fc9f-4b2f-9792-e02a842b1766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'dokumen' and @type = 'text']</value>
      <webElementGuid>287dcd30-32b8-4aa4-980c-122072a5126d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
