<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Jenis Baru</name>
   <tag></tag>
   <elementGuidId>d275cc83-2fa4-4d34-bfdb-104ad9b17282</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//li[@id=''])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>0e97499f-439d-4597-a394-408efe637172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>54a1f1e5-678e-4b0a-9e31-58aabaad39fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-element p-dropdown-item</value>
      <webElementGuid>bcb9eafc-1ee7-406a-bd0d-a34702731e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Jenis Baru</value>
      <webElementGuid>e5987f10-eeaa-4db1-aebf-5528ecb8d617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>953c4ea5-af49-4957-b59d-9a9335bf7118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jenis Baru</value>
      <webElementGuid>3428e1d3-a934-4f9d-b7e2-90d9f637208d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr_id_50_list&quot;)/p-dropdownitem[@class=&quot;p-element ng-tns-c70-47 ng-star-inserted&quot;]/li[@class=&quot;p-ripple p-element p-dropdown-item&quot;]</value>
      <webElementGuid>4f309214-fcce-4cae-abf6-e1e7720075ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//li[@id=''])[4]</value>
      <webElementGuid>3436fba0-9860-468a-92a3-b69b5e222c3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='pr_id_50_list']/p-dropdownitem[5]/li</value>
      <webElementGuid>8c15367f-80a0-4ac6-aaf0-4f340525b9fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis 003'])[1]/following::li[1]</value>
      <webElementGuid>385323e5-7a26-4126-81f1-bc3379c0b90c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='jenis3'])[1]/following::li[2]</value>
      <webElementGuid>23a365be-79d1-45f1-bd59-32bd1b9aeeb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Lama'])[1]/preceding::li[1]</value>
      <webElementGuid>8a5b2013-66f5-4cf8-8f3c-2cfa8a0b3f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-dropdownitem[5]/li</value>
      <webElementGuid>2d9c612c-485a-45e3-8429-2a81203ce263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Jenis Baru' or . = 'Jenis Baru')]</value>
      <webElementGuid>d4e55158-7e4e-48f2-b4de-7cde2e4d8abd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
