<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Judul Kontrak_judulKontrak</name>
   <tag></tag>
   <elementGuidId>664c6e8f-adb1-4a95-91f4-bf15a8cfda76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='judulKontrak']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#judulKontrak</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>648def01-a0aa-46f2-ac31-7040f0bbd393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>judulKontrak</value>
      <webElementGuid>75f0616c-8f05-4679-a8f5-36c4b6a17f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>judulKontrak</value>
      <webElementGuid>29243ba5-31ac-4ce7-96d6-2c647473c9b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4bc78014-b014-43c1-b9e9-5d8bd600a937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>3d558c29-8e87-4346-8f31-23d607aabc18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-base text-color surface-overlay p-2 border-1 border-solid border-500 appearance-none outline-none focus:border-primary w-full ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>c0475aa9-7cc1-46bc-9601-b810b05e49ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;judulKontrak&quot;)</value>
      <webElementGuid>664b83ee-bbad-432e-a3f8-cfdffd79a57a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='judulKontrak']</value>
      <webElementGuid>1ab0342c-62cd-464b-92ec-5afc8d1c4b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>72ef50d9-d5c2-4fc5-800d-b8a358557a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'judulKontrak' and @type = 'text']</value>
      <webElementGuid>1a359297-65a4-45dc-ac79-52fce11ff22c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
