<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Daftar Termin</name>
   <tag></tag>
   <elementGuidId>30a4e426-cb5f-4e84-aa3d-4a09b199586d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='p-tabpanel-4-label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#p-tabpanel-4-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4ead08c5-0554-4494-9db8-bfe438a1470a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>8dfaf962-a68a-4606-a9a4-bd24a50520de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element p-ripple p-tabview-nav-link</value>
      <webElementGuid>f5d1b1e8-ea49-4832-88cf-9c5412cf4d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>p-tabpanel-4-label</value>
      <webElementGuid>85c35e67-ec22-4839-a294-6d56b5b8f273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>p-tabpanel-4</value>
      <webElementGuid>7d16d10b-28b2-46c8-833d-e47a18a2076c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4333c5fe-6918-4bbf-808b-36d2480452f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar Termin</value>
      <webElementGuid>115957a8-1b02-447b-81ba-863b6c65c148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-4-label&quot;)</value>
      <webElementGuid>50ff355f-3d1b-4760-a6d4-87be30d5c3de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='p-tabpanel-4-label']</value>
      <webElementGuid>671f48fc-6cd9-4f18-af50-72de147314a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Direksi Pekerjaan'])[1]/following::a[1]</value>
      <webElementGuid>6ca7f0f9-fc2f-4f28-90dd-f7270c87e4e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar PO'])[1]/following::a[2]</value>
      <webElementGuid>86ce37db-dc67-41fb-b29e-163960075877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Dokumen Post Kontrak'])[1]/preceding::a[1]</value>
      <webElementGuid>3e4e7add-6b09-4746-862f-469facc3e35d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]/a</value>
      <webElementGuid>7541ea21-74ba-490c-9329-64b2f87fba9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'p-tabpanel-4-label' and (text() = 'Daftar Termin' or . = 'Daftar Termin')]</value>
      <webElementGuid>aa8cc71a-7e47-40a5-be0b-1ff68151aa14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
