<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Daftar Dokumen Post Kontrak</name>
   <tag></tag>
   <elementGuidId>b7a29464-d766-4f29-96bc-856434bba520</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='p-tabpanel-5-label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#p-tabpanel-5-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f0a92bad-d245-4d0b-b654-c6acfd6bb0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>c2eb224f-fab4-40fd-b188-16106b87f060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element p-ripple p-tabview-nav-link</value>
      <webElementGuid>55c75802-c091-4e15-816f-ecabe4f1af18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>p-tabpanel-5-label</value>
      <webElementGuid>8abdb313-6dc7-4109-8758-1dee97cf598b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>p-tabpanel-5</value>
      <webElementGuid>ed5520a9-e644-4502-ab6f-2c2830ca4bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b86209bf-6e28-4bec-b050-a197a6789686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar Dokumen Post Kontrak</value>
      <webElementGuid>25aeed62-066d-44da-b100-0142d440d90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-5-label&quot;)</value>
      <webElementGuid>5e6597e2-87ca-431f-83e0-d0c04026384a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='p-tabpanel-5-label']</value>
      <webElementGuid>82d40444-dd22-4d85-ad5b-81546386d2b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Termin'])[1]/following::a[1]</value>
      <webElementGuid>c89d6315-e9d0-4eca-8b0c-c08ed6053bd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Direksi Pekerjaan'])[1]/following::a[2]</value>
      <webElementGuid>e9b53e69-f6dc-4aac-a1c9-3f72933ed0a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baru'])[1]/preceding::a[1]</value>
      <webElementGuid>71cd18f8-74df-42a9-8d78-fab8bceef247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>0e905b55-c3bc-404e-a236-f494793bed42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'p-tabpanel-5-label' and (text() = 'Daftar Dokumen Post Kontrak' or . = 'Daftar Dokumen Post Kontrak')]</value>
      <webElementGuid>782319bf-675d-42a7-b285-9027f16a7a83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
