<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Daftar Dokumen Post Kontrak</name>
   <tag></tag>
   <elementGuidId>295c5740-9ee6-47c9-a85c-a61f4b994c36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='p-tabpanel-5-label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#p-tabpanel-5-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4b9c23fe-9256-4bfe-a7e2-383886c49446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>3b77bead-4199-477d-9a37-82b20b231b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element p-ripple p-tabview-nav-link</value>
      <webElementGuid>f55051fe-f906-45f2-ba8e-987ceb7ded31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>p-tabpanel-5-label</value>
      <webElementGuid>fa519b1e-9160-44cb-b2df-a7d211a25297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>p-tabpanel-5</value>
      <webElementGuid>4e5fcb68-99ab-47e7-b82e-c04bb0c1298c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4db0ea08-9384-407d-9825-90beccf78a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar Dokumen Post Kontrak</value>
      <webElementGuid>f4727ed6-34de-497a-ba81-d613888efb1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-5-label&quot;)</value>
      <webElementGuid>ef8e96ed-dcb9-4bf1-96ff-1d376e455087</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='p-tabpanel-5-label']</value>
      <webElementGuid>86cf7fb6-adbd-4e35-89bb-4152287d54b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Termin'])[1]/following::a[1]</value>
      <webElementGuid>2fe4b2bf-6be2-4338-bb62-acf654738c96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Direksi Pekerjaan'])[1]/following::a[2]</value>
      <webElementGuid>35d38cc8-ad93-4798-a133-0a95f4de9604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baru'])[1]/preceding::a[1]</value>
      <webElementGuid>97b92c29-3b11-4bbf-89eb-778c51a605e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>eec33cd9-e63b-42bc-a6dc-e598ad1eab52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'p-tabpanel-5-label' and (text() = 'Daftar Dokumen Post Kontrak' or . = 'Daftar Dokumen Post Kontrak')]</value>
      <webElementGuid>ef78d129-4e41-438f-86c8-a283f869c6a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
