<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama_namaDok</name>
   <tag></tag>
   <elementGuidId>d275e9d2-096d-4a3d-9f89-6ad642d57366</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='namaDok']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#namaDok</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b520dcb-1a2d-46a6-92ed-23a20f25c1ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>namaDok</value>
      <webElementGuid>602b127b-5374-4f94-acbd-c496323cf60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>namaDok</value>
      <webElementGuid>0c4bf3f3-9838-44d0-9119-db03d61c0d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f412bcbc-d9f6-4795-9b5e-374ca2baea81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm text-color surface-overlay p-2 border-1 border-solid border-500 appearance-none outline-none focus:border-primary w-full h-custom ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>21f1578f-04d4-4b7b-80f9-086fce98b0b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;namaDok&quot;)</value>
      <webElementGuid>3dc18ba6-c29f-4fb5-a409-f1e94c31969f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='namaDok']</value>
      <webElementGuid>d24dabd9-bc5d-4974-9d79-cc5e77c10f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p-tabpanel-5']/jhi-payablegw-dokpostkontrak-list/jhi-payablegw-formdokpostkontrak/p-dialog/div/div/div[2]/form/div/div[2]/div/div/input</value>
      <webElementGuid>7f2c58aa-ef38-48fa-a5ad-bb4c9a237909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>caaa06b5-d9b5-43bc-a335-7020d0e706b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'namaDok' and @type = 'text']</value>
      <webElementGuid>910b42fa-9d3f-49e8-80b9-06f22a07dda8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
