<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_10</name>
   <tag></tag>
   <elementGuidId>c64043f8-26f1-47de-ab94-5633149bee76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p-calendar[@id='tanggal']/span/div/div/div/div[2]/table/tbody/tr[3]/td[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>13938ea0-3809-433a-8791-c3154ecb5cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8294f6a5-6769-4cf4-b03c-b9db4ab63dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-ripple p-element ng-tns-c83-43 ng-star-inserted</value>
      <webElementGuid>6224d1c9-c270-46c6-9b5d-d85b526a038c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>519c175b-adfb-4eb1-806b-80fd92ebe7a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-5&quot;)/jhi-payablegw-dokpostkontrak-list[1]/jhi-payablegw-formdokpostkontrak[1]/p-dialog[@class=&quot;p-element ng-tns-c110-41 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c110-41 p-dialog-mask p-component-overlay p-component-overlay-enter p-dialog-mask-scrollblocker ng-star-inserted&quot;]/div[@class=&quot;p-element ng-trigger ng-trigger-animation ng-tns-c110-41 p-dialog p-component ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c110-41 p-dialog-content&quot;]/form[@class=&quot;ng-valid ng-star-inserted ng-dirty ng-touched&quot;]/div[@class=&quot;grid -mx-1&quot;]/div[@class=&quot;col-12 px-1&quot;]/div[@class=&quot;field grid -mx-1&quot;]/div[@class=&quot;px-1 col-3&quot;]/p-calendar[@id=&quot;tanggal&quot;]/span[@class=&quot;ng-tns-c83-43 p-calendar p-calendar-w-btn&quot;]/div[@class=&quot;ng-trigger ng-trigger-overlayAnimation ng-tns-c83-43 p-datepicker p-component ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-group-container ng-tns-c83-43 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-group ng-tns-c83-43 ng-star-inserted&quot;]/div[@class=&quot;p-datepicker-calendar-container ng-tns-c83-43 ng-star-inserted&quot;]/table[@class=&quot;p-datepicker-calendar ng-tns-c83-43&quot;]/tbody[@class=&quot;ng-tns-c83-43&quot;]/tr[@class=&quot;ng-tns-c83-43 ng-star-inserted&quot;]/td[@class=&quot;ng-tns-c83-43 ng-star-inserted&quot;]/span[@class=&quot;p-ripple p-element ng-tns-c83-43 ng-star-inserted&quot;]</value>
      <webElementGuid>71927ed9-c7e4-476d-8201-d311aa1c7385</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-calendar[@id='tanggal']/span/div/div/div/div[2]/table/tbody/tr[3]/td[2]/span</value>
      <webElementGuid>aa663ee0-66be-4b57-921f-22eed8923559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[31]</value>
      <webElementGuid>e158f740-1565-4ae9-a11d-8a8f9955a766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[1]/following::span[32]</value>
      <webElementGuid>abca533f-304f-436d-b8ce-86ecfb62d512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama'])[3]/preceding::span[54]</value>
      <webElementGuid>2d5804e4-0188-4d6d-9932-8f2ad3fee88c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keterangan'])[4]/preceding::span[54]</value>
      <webElementGuid>d9fdb08c-fb1a-4a59-ac15-0d30eaec8e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='10']/parent::*</value>
      <webElementGuid>0ff75e9a-cd08-485b-a7a2-d8841f48c1c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/span</value>
      <webElementGuid>af946ccb-bae8-470b-a590-adb711ea9c25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '10' or . = '10')]</value>
      <webElementGuid>0fb716ab-38a8-488b-8dd5-fa7fbbc8d0ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
