<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Keterangan_keterangan</name>
   <tag></tag>
   <elementGuidId>4b57daa7-d551-4a36-a3cd-52d77daa4567</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='keterangan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-12.px-1.-mt-6 > div.field.grid.-mx-1 > div.px-1.col > #keterangan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>09107765-d619-480c-a16f-27ee9a5532e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>keterangan</value>
      <webElementGuid>e7b2ac80-43f9-4983-8e43-e8d525f8ae9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>keterangan</value>
      <webElementGuid>d26d75cf-4d4d-4da0-a368-65cbb5cd2b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e14bd4a5-e300-4c28-9f45-756f5c320c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>83399c8b-d38a-4ffb-b74a-6f85c1aaff34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-base text-color surface-overlay p-2 border-1 border-solid border-500 appearance-none outline-none focus:border-primary w-full ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>10d40bb1-f899-45af-ba4a-0192d1dfc114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-5&quot;)/jhi-payablegw-dokpostkontrak-list[1]/jhi-payablegw-formdokpostkontrak[1]/p-dialog[@class=&quot;p-element ng-tns-c110-41 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c110-41 p-dialog-mask p-component-overlay p-component-overlay-enter p-dialog-mask-scrollblocker ng-star-inserted&quot;]/div[@class=&quot;p-element ng-trigger ng-trigger-animation ng-tns-c110-41 p-dialog p-component ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c110-41 p-dialog-content&quot;]/form[@class=&quot;ng-valid ng-star-inserted ng-dirty ng-touched&quot;]/div[@class=&quot;grid -mx-1&quot;]/div[@class=&quot;col-12 px-1 -mt-6&quot;]/div[@class=&quot;field grid -mx-1&quot;]/div[@class=&quot;px-1 col&quot;]/textarea[@id=&quot;keterangan&quot;]</value>
      <webElementGuid>cf7731cf-b10d-4da2-ba34-e26cc46d2049</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='keterangan']</value>
      <webElementGuid>88bcfc1d-3337-4b0f-a4ea-1aaac4650cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p-tabpanel-5']/jhi-payablegw-dokpostkontrak-list/jhi-payablegw-formdokpostkontrak/p-dialog/div/div/div[2]/form/div/div[3]/div/div/textarea</value>
      <webElementGuid>3b8224a8-e5c1-4b49-ab36-d129878a3e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/textarea</value>
      <webElementGuid>d6c6edab-fbc6-48dc-b003-95dfc76d3ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'keterangan' and @type = 'text']</value>
      <webElementGuid>6a345090-98a9-4a85-b118-b61fba671f17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
