<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_-- Pilih --_p-dropdown-trigger ng-tns-c70-26</name>
   <tag></tag>
   <elementGuidId>a713e25e-1200-4101-bf36-ac45ca40a2ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p-dropdown[@id='unitPenagihan']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.p-dropdown-trigger.ng-tns-c70-26</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>27070b7d-749c-45ef-a171-f61ae356b6a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ca1b5d93-9d85-42da-9615-a255ba8ecde7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>dropdown trigger</value>
      <webElementGuid>e264a810-04ce-4044-b2be-56edb0ff182a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>a2864b1a-f8f6-4835-ae90-c2a74dcc245e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-dropdown-trigger ng-tns-c70-26</value>
      <webElementGuid>c3c51bcb-1944-4382-9165-88e1154db84c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unitPenagihan&quot;)/div[@class=&quot;ng-tns-c70-26 p-dropdown p-component p-dropdown-clearable&quot;]/div[@class=&quot;p-dropdown-trigger ng-tns-c70-26&quot;]</value>
      <webElementGuid>0e601232-5fe4-45e1-bc50-8c393a3dd31f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p-dropdown[@id='unitPenagihan']/div/div[2]</value>
      <webElementGuid>418e2749-129c-4be1-bc6b-d3d63a94de36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Pilih --'])[2]/following::div[1]</value>
      <webElementGuid>20fb199c-fc3b-4dc6-9e10-88f70daafdb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit Penagihan'])[1]/following::div[4]</value>
      <webElementGuid>de9fa4dd-8adf-4b6f-bdac-ed8f79e5b994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vendor'])[1]/preceding::div[1]</value>
      <webElementGuid>dae1b877-2f7c-47eb-9388-ab16c8744bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Judul Kontrak'])[1]/preceding::div[7]</value>
      <webElementGuid>64db724b-1237-4ebe-b8d7-d81dd4e43690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p-dropdown/div/div[2]</value>
      <webElementGuid>4062c152-4726-4490-92a4-347057d9e92a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
