<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Presentase_persentase</name>
   <tag></tag>
   <elementGuidId>18bfebd0-3155-4462-b29c-0cf33637bcd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#persentase</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='persentase']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a54c5a36-4ad4-4822-b3b8-2f544a0dd75d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>persentase</value>
      <webElementGuid>7bfb0e97-dda2-4bb4-a0e9-7bf16efdb4c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>persentase</value>
      <webElementGuid>005bbd28-9dee-44d0-a66c-8d3722377a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>7dae1212-0cda-4593-a993-79adfe883786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm text-color surface-overlay p-2 border-1 border-solid border-500 appearance-none outline-none focus:border-primary w-full h-custom ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>a88ba2ab-6963-4c9a-8c18-a612a2256084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;persentase&quot;)</value>
      <webElementGuid>9e264e10-a5cc-4821-8ffc-dd8ae776b32f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='persentase']</value>
      <webElementGuid>a1a0ecf8-ca7c-4e6c-bc06-3a7e5f4013b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p-tabpanel-4']/jhi-payablegw-termin-list/jhi-payablegw-formtermin/form/p-dialog/div/div/div[2]/div/div[3]/div/div/input</value>
      <webElementGuid>fc6c63bb-67ad-4cab-bd4a-85199d8427ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div/div/input</value>
      <webElementGuid>d2755013-5034-4fc1-9724-58b1c4725046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'persentase' and @type = 'number']</value>
      <webElementGuid>1c1a86e2-062b-4f7a-8450-9e2a82203f06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
