<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Daftar Direksi Pekerjaan</name>
   <tag></tag>
   <elementGuidId>48c7dcab-650f-4fe8-a96f-e61fe474d8b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='p-tabpanel-3-label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#p-tabpanel-3-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8ffd4ce1-842a-42ca-8a33-fdf65a17c9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>279d2129-d7c2-477f-bfbe-8b0b951a5989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element p-ripple p-tabview-nav-link</value>
      <webElementGuid>c160b231-3c46-4f68-b743-885ca2f91e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>p-tabpanel-3-label</value>
      <webElementGuid>1a0c6012-001e-454a-b415-55148e0d8fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>p-tabpanel-3</value>
      <webElementGuid>5a3d6c3f-0b12-42a4-a9a4-d1c65a2b2c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>00f99da0-3db0-4c81-9dfc-ebb64d05fe2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar Direksi Pekerjaan</value>
      <webElementGuid>1c6c7a7e-639f-4b91-a816-16d2e447a766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-3-label&quot;)</value>
      <webElementGuid>72af0900-f0d9-42f2-91b8-28492f3bdf93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='p-tabpanel-3-label']</value>
      <webElementGuid>0a51e782-91e9-44dd-b2df-a4b34574266c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar PO'])[1]/following::a[1]</value>
      <webElementGuid>b76669fe-9e44-457c-a5db-6383b24d2fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tim Pemeriksa Penyelesaian Pekerjaan'])[1]/following::a[2]</value>
      <webElementGuid>88a06172-d491-4981-9fc0-9f6053fdbcb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Termin'])[1]/preceding::a[1]</value>
      <webElementGuid>1fdb326f-0142-4886-8996-9eb6404a491f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[2]/a</value>
      <webElementGuid>4c84984c-e8d7-4c94-9cff-f8329fefa104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'p-tabpanel-3-label' and (text() = 'Daftar Direksi Pekerjaan' or . = 'Daftar Direksi Pekerjaan')]</value>
      <webElementGuid>668067fe-3b82-4af3-b813-a28ce6f39448</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
