<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Daftar Termin</name>
   <tag></tag>
   <elementGuidId>25eec098-676f-44b7-8afe-da53409c1d35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#p-tabpanel-4-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='p-tabpanel-4-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1fce0270-8ebc-4f3e-99b8-9216d072ee74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>17ca1583-f7d6-435c-8801-deaa0e3c09f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element p-ripple p-tabview-nav-link</value>
      <webElementGuid>2833fb83-cc05-45b6-9155-a92a94d5e754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>p-tabpanel-4-label</value>
      <webElementGuid>960b163e-1b61-4dda-86c9-c855ecf99ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>p-tabpanel-4</value>
      <webElementGuid>0a733e88-112f-42a6-948c-7f73c5a06d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f1caf22b-66bd-4c23-a762-3b139163b5d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar Termin</value>
      <webElementGuid>4b1836c6-b517-4f38-9bd4-762e90ff3016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-4-label&quot;)</value>
      <webElementGuid>6c66b927-4a95-4535-8579-e19d78cb38e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='p-tabpanel-4-label']</value>
      <webElementGuid>dea8ece7-c5c4-45e3-ac87-a341d9987568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Direksi Pekerjaan'])[1]/following::a[1]</value>
      <webElementGuid>85236db9-a0f7-42d7-9c4d-1a0c342c8eaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar PO'])[1]/following::a[2]</value>
      <webElementGuid>b49875f5-8464-420d-bf18-e096bd109cd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Dokumen Post Kontrak'])[1]/preceding::a[1]</value>
      <webElementGuid>8af6829e-1915-428d-b055-71134e5d3874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[3]/a</value>
      <webElementGuid>191bda2b-d90b-4c7b-9ebf-9658eb2a2e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'p-tabpanel-4-label' and (text() = 'Daftar Termin' or . = 'Daftar Termin')]</value>
      <webElementGuid>7ec654ba-9b6a-4e65-abd5-68d9fc1a7379</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
