<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Syarat Penyerahan Barang dan Jasa</name>
   <tag></tag>
   <elementGuidId>377b9d74-d705-4fc8-8935-e24593a505e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.p-element.p-button-sm.p-button-info.p-button.p-component</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[17]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>24a15262-8a4e-4ac7-9fbb-aaff944048e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Syarat Penyerahan Barang dan Jasa</value>
      <webElementGuid>a20881d9-8a39-4c5d-be4e-0ddfa8135ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon</name>
      <type>Main</type>
      <value>pi pi-clone</value>
      <webElementGuid>af0a4b6f-a5dc-4418-8f72-5e213f64fb03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>003c2ee6-9a4f-439a-84cd-8329b1b3127f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element p-button-sm p-button-info p-button p-component</value>
      <webElementGuid>9381e95a-09e5-4cb9-b056-b7f42fbe9897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Syarat Penyerahan Barang dan Jasa</value>
      <webElementGuid>14256599-bef1-4a4b-9ed1-1a9ba7349ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;p-tabpanel-4&quot;)/jhi-payablegw-termin-list[1]/div[@class=&quot;mb-2&quot;]/button[@class=&quot;p-element p-button-sm p-button-info p-button p-component&quot;]</value>
      <webElementGuid>2808a5d5-5f17-4632-bf1b-6a37361f98e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[17]</value>
      <webElementGuid>c5a04f42-74db-4398-93b0-b52631f0412f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='p-tabpanel-4']/jhi-payablegw-termin-list/div/button[4]</value>
      <webElementGuid>911c06d7-ad18-48b8-96de-09d477c45a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus'])[3]/following::button[1]</value>
      <webElementGuid>a80b18d2-f7df-46af-8ba2-b9ec943fac6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::button[2]</value>
      <webElementGuid>9de14d9c-af39-433b-8740-403116866baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syarat Pembayaran'])[1]/preceding::button[1]</value>
      <webElementGuid>d3de6fb0-3944-440a-9224-6cd583ddb6a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>03360282-9f44-4ffc-b944-d96379f7c6cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Syarat Penyerahan Barang dan Jasa' or . = 'Syarat Penyerahan Barang dan Jasa')]</value>
      <webElementGuid>87f19109-c022-4c3d-91ed-2fe53f355df2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
